// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/systemd.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/systemd.go -destination=tests/mocks/mock_systemd.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSystemdConnection is a mock of SystemdConnection interface.
type MockSystemdConnection struct {
	ctrl     *gomock.Controller
	recorder *MockSystemdConnectionMockRecorder
	isgomock struct{}
}

// MockSystemdConnectionMockRecorder is the mock recorder for MockSystemdConnection.
type MockSystemdConnectionMockRecorder struct {
	mock *MockSystemdConnection
}

// NewMockSystemdConnection creates a new mock instance.
func NewMockSystemdConnection(ctrl *gomock.Controller) *MockSystemdConnection {
	mock := &MockSystemdConnection{ctrl: ctrl}
	mock.recorder = &MockSystemdConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemdConnection) EXPECT() *MockSystemdConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSystemdConnection) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSystemdConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSystemdConnection)(nil).Close))
}

// DisableUnit mocks base method.
func (m *MockSystemdConnection) DisableUnit(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableUnit", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableUnit indicates an expected call of DisableUnit.
func (mr *MockSystemdConnectionMockRecorder) DisableUnit(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableUnit", reflect.TypeOf((*MockSystemdConnection)(nil).DisableUnit), ctx, name)
}

// EnableUnit mocks base method.
func (m *MockSystemdConnection) EnableUnit(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableUnit", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableUnit indicates an expected call of EnableUnit.
func (mr *MockSystemdConnectionMockRecorder) EnableUnit(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableUnit", reflect.TypeOf((*MockSystemdConnection)(nil).EnableUnit), ctx, name)
}

// GetUnitProperty mocks base method.
func (m *MockSystemdConnection) GetUnitProperty(ctx context.Context, unit, property string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnitProperty", ctx, unit, property)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnitProperty indicates an expected call of GetUnitProperty.
func (mr *MockSystemdConnectionMockRecorder) GetUnitProperty(ctx, unit, property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnitProperty", reflect.TypeOf((*MockSystemdConnection)(nil).GetUnitProperty), ctx, unit, property)
}

// MaskUnit mocks base method.
func (m *MockSystemdConnection) MaskUnit(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaskUnit", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// MaskUnit indicates an expected call of MaskUnit.
func (mr *MockSystemdConnectionMockRecorder) MaskUnit(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaskUnit", reflect.TypeOf((*MockSystemdConnection)(nil).MaskUnit), ctx, name)
}

// ReloadUnit mocks base method.
func (m *MockSystemdConnection) ReloadUnit(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadUnit", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadUnit indicates an expected call of ReloadUnit.
func (mr *MockSystemdConnectionMockRecorder) ReloadUnit(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadUnit", reflect.TypeOf((*MockSystemdConnection)(nil).ReloadUnit), ctx, name)
}

// RestartUnit mocks base method.
func (m *MockSystemdConnection) RestartUnit(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartUnit", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestartUnit indicates an expected call of RestartUnit.
func (mr *MockSystemdConnectionMockRecorder) RestartUnit(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartUnit", reflect.TypeOf((*MockSystemdConnection)(nil).RestartUnit), ctx, name)
}

// StartUnit mocks base method.
func (m *MockSystemdConnection) StartUnit(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartUnit", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartUnit indicates an expected call of StartUnit.
func (mr *MockSystemdConnectionMockRecorder) StartUnit(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartUnit", reflect.TypeOf((*MockSystemdConnection)(nil).StartUnit), ctx, name)
}

// StopUnit mocks base method.
func (m *MockSystemdConnection) StopUnit(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopUnit", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopUnit indicates an expected call of StopUnit.
func (mr *MockSystemdConnectionMockRecorder) StopUnit(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopUnit", reflect.TypeOf((*MockSystemdConnection)(nil).StopUnit), ctx, name)
}

// UnmaskUnit mocks base method.
func (m *MockSystemdConnection) UnmaskUnit(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmaskUnit", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmaskUnit indicates an expected call of UnmaskUnit.
func (mr *MockSystemdConnectionMockRecorder) UnmaskUnit(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmaskUnit", reflect.TypeOf((*MockSystemdConnection)(nil).UnmaskUnit), ctx, name)
}
