// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/reboot_decision.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/reboot_decision.go -destination=tests/mocks/mock_rmc_fetcher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1alpha1 "in-cloud.io/machine-config/api/v1alpha1"
)

// MockRMCFetcher is a mock of RMCFetcher interface.
type MockRMCFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockRMCFetcherMockRecorder
	isgomock struct{}
}

// MockRMCFetcherMockRecorder is the mock recorder for MockRMCFetcher.
type MockRMCFetcherMockRecorder struct {
	mock *MockRMCFetcher
}

// NewMockRMCFetcher creates a new mock instance.
func NewMockRMCFetcher(ctrl *gomock.Controller) *MockRMCFetcher {
	mock := &MockRMCFetcher{ctrl: ctrl}
	mock.recorder = &MockRMCFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRMCFetcher) EXPECT() *MockRMCFetcherMockRecorder {
	return m.recorder
}

// FetchRMC mocks base method.
func (m *MockRMCFetcher) FetchRMC(ctx context.Context, name string) (*v1alpha1.RenderedMachineConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRMC", ctx, name)
	ret0, _ := ret[0].(*v1alpha1.RenderedMachineConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRMC indicates an expected call of FetchRMC.
func (mr *MockRMCFetcherMockRecorder) FetchRMC(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRMC", reflect.TypeOf((*MockRMCFetcher)(nil).FetchRMC), ctx, name)
}
