// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/reboot/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/reboot/handler.go -destination=tests/mocks/mock_reboot.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNodeAnnotationWriter is a mock of NodeAnnotationWriter interface.
type MockNodeAnnotationWriter struct {
	ctrl     *gomock.Controller
	recorder *MockNodeAnnotationWriterMockRecorder
	isgomock struct{}
}

// MockNodeAnnotationWriterMockRecorder is the mock recorder for MockNodeAnnotationWriter.
type MockNodeAnnotationWriterMockRecorder struct {
	mock *MockNodeAnnotationWriter
}

// NewMockNodeAnnotationWriter creates a new mock instance.
func NewMockNodeAnnotationWriter(ctrl *gomock.Controller) *MockNodeAnnotationWriter {
	mock := &MockNodeAnnotationWriter{ctrl: ctrl}
	mock.recorder = &MockNodeAnnotationWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeAnnotationWriter) EXPECT() *MockNodeAnnotationWriterMockRecorder {
	return m.recorder
}

// ClearForceReboot mocks base method.
func (m *MockNodeAnnotationWriter) ClearForceReboot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearForceReboot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearForceReboot indicates an expected call of ClearForceReboot.
func (mr *MockNodeAnnotationWriterMockRecorder) ClearForceReboot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearForceReboot", reflect.TypeOf((*MockNodeAnnotationWriter)(nil).ClearForceReboot), ctx)
}

// SetCurrentRevision mocks base method.
func (m *MockNodeAnnotationWriter) SetCurrentRevision(ctx context.Context, revision string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentRevision", ctx, revision)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentRevision indicates an expected call of SetCurrentRevision.
func (mr *MockNodeAnnotationWriterMockRecorder) SetCurrentRevision(ctx, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentRevision", reflect.TypeOf((*MockNodeAnnotationWriter)(nil).SetCurrentRevision), ctx, revision)
}

// SetRebootPending mocks base method.
func (m *MockNodeAnnotationWriter) SetRebootPending(ctx context.Context, pending bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRebootPending", ctx, pending)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRebootPending indicates an expected call of SetRebootPending.
func (mr *MockNodeAnnotationWriterMockRecorder) SetRebootPending(ctx, pending any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRebootPending", reflect.TypeOf((*MockNodeAnnotationWriter)(nil).SetRebootPending), ctx, pending)
}

// SetState mocks base method.
func (m *MockNodeAnnotationWriter) SetState(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockNodeAnnotationWriterMockRecorder) SetState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockNodeAnnotationWriter)(nil).SetState), ctx, state)
}

// MockRebootExecutor is a mock of RebootExecutor interface.
type MockRebootExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockRebootExecutorMockRecorder
	isgomock struct{}
}

// MockRebootExecutorMockRecorder is the mock recorder for MockRebootExecutor.
type MockRebootExecutorMockRecorder struct {
	mock *MockRebootExecutor
}

// NewMockRebootExecutor creates a new mock instance.
func NewMockRebootExecutor(ctrl *gomock.Controller) *MockRebootExecutor {
	mock := &MockRebootExecutor{ctrl: ctrl}
	mock.recorder = &MockRebootExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRebootExecutor) EXPECT() *MockRebootExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRebootExecutor) Execute(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRebootExecutorMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRebootExecutor)(nil).Execute), ctx)
}
