// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/files.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/files.go -destination=tests/mocks/mock_files.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1alpha1 "in-cloud.io/machine-config/api/v1alpha1"
	agent "in-cloud.io/machine-config/internal/agent"
)

// MockFileOperations is a mock of FileOperations interface.
type MockFileOperations struct {
	ctrl     *gomock.Controller
	recorder *MockFileOperationsMockRecorder
	isgomock struct{}
}

// MockFileOperationsMockRecorder is the mock recorder for MockFileOperations.
type MockFileOperationsMockRecorder struct {
	mock *MockFileOperations
}

// NewMockFileOperations creates a new mock instance.
func NewMockFileOperations(ctrl *gomock.Controller) *MockFileOperations {
	mock := &MockFileOperations{ctrl: ctrl}
	mock.recorder = &MockFileOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileOperations) EXPECT() *MockFileOperationsMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockFileOperations) Apply(f v1alpha1.FileSpec) agent.FileApplyResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", f)
	ret0, _ := ret[0].(agent.FileApplyResult)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockFileOperationsMockRecorder) Apply(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockFileOperations)(nil).Apply), f)
}

// ApplyAll mocks base method.
func (m *MockFileOperations) ApplyAll(files []v1alpha1.FileSpec) ([]agent.FileApplyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyAll", files)
	ret0, _ := ret[0].([]agent.FileApplyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyAll indicates an expected call of ApplyAll.
func (mr *MockFileOperationsMockRecorder) ApplyAll(files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyAll", reflect.TypeOf((*MockFileOperations)(nil).ApplyAll), files)
}

// NeedsUpdate mocks base method.
func (m *MockFileOperations) NeedsUpdate(f v1alpha1.FileSpec) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedsUpdate", f)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NeedsUpdate indicates an expected call of NeedsUpdate.
func (mr *MockFileOperationsMockRecorder) NeedsUpdate(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedsUpdate", reflect.TypeOf((*MockFileOperations)(nil).NeedsUpdate), f)
}
