version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - errcheck
          - goconst
          - unparam
          - ineffassign
          - staticcheck
        path: _test\.go$
      # syscall.Sync is fire-and-forget
      - linters:
          - errcheck
        path: internal/agent/reboot/executor\.go
        text: "syscall.Sync"
      # Complex reconcile function - acceptable
      - linters:
          - gocyclo
        path: internal/controller/machineconfigpool_controller\.go
      # log := log.FromContext is idiomatic pattern
      - linters:
          - revive
        text: "import-shadowing.*log"
      # prealloc is a suggestion, not required
      - linters:
          - prealloc
        path: internal/controller/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
