# Basic worker pool configuration
# Selects nodes with node-role.kubernetes.io/worker label
apiVersion: mco.in-cloud.io/v1alpha1
kind: MachineConfigPool
metadata:
  name: worker
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
  machineConfigSelector:
    matchLabels:
      mco.in-cloud.io/pool: worker
  rollout:
    maxUnavailable: 1
    debounceSeconds: 30
  reboot:
    strategy: Never
  revisionHistory:
    limit: 5

