# File management example
# Demonstrates creating files with different permissions and deleting files
apiVersion: mco.in-cloud.io/v1alpha1
kind: MachineConfig
metadata:
  name: file-management
  labels:
    mco.in-cloud.io/pool: worker
spec:
  priority: 50
  files:
    # Create a regular config file (0644)
    - path: /etc/myapp/config.yaml
      content: |
        server:
          port: 8080
          host: 0.0.0.0
      mode: 420
      owner: "root:root"
    
    # Create a private file (0600)
    - path: /etc/myapp/secret.key
      content: "secret-content-here"
      mode: 384
      owner: "root:root"
    
    # Delete a legacy file
    - path: /etc/legacy/old-config.conf
      state: absent

