# =============================================================================
# Reboot Strategy Examples
# =============================================================================
#
# This example demonstrates different reboot strategies.
#
# What it does:
#   - Shows pool with Never strategy (manual reboots)
#   - Shows pool with IfRequired strategy (auto reboots)
#   - Shows MachineConfig that requires reboot
#
# Key concepts:
#   - Never: Nodes never reboot automatically
#   - IfRequired: Nodes reboot if MachineConfig.reboot.required=true
#   - minIntervalSeconds: Minimum time between reboots
#
# Apply:
#   kubectl apply -f 02-reboot-strategy.yaml
#
# Check pending reboots:
#   kubectl get nodes -o json | jq -r '.items[] |
#     select(.metadata.annotations["mco.in-cloud.io/reboot-pending"] == "true") |
#     .metadata.name'
#
# =============================================================================

---
# =============================================================================
# Pool: Production (Never reboots)
# =============================================================================
# Use this for production workloads where you want full control over reboots
apiVersion: mco.in-cloud.io/v1alpha1
kind: MachineConfigPool
metadata:
  name: production
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
      environment: production
  machineConfigSelector:
    matchLabels:
      mco.in-cloud.io/pool: production
  rollout:
    debounceSeconds: 60
    applyTimeoutSeconds: 900
  reboot:
    # NEVER reboot automatically
    # Nodes will have reboot-pending annotation when reboot is needed
    # Admin must reboot manually during maintenance window
    strategy: Never
  revisionHistory:
    limit: 10
  paused: false

---
# =============================================================================
# Pool: Development (Auto reboots)
# =============================================================================
# Use this for dev/test where auto-reboot is acceptable
apiVersion: mco.in-cloud.io/v1alpha1
kind: MachineConfigPool
metadata:
  name: development
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
      environment: development
  machineConfigSelector:
    matchLabels:
      mco.in-cloud.io/pool: development
  rollout:
    debounceSeconds: 10
    applyTimeoutSeconds: 300
  reboot:
    # Automatically reboot when MachineConfig requires it
    strategy: IfRequired
    # Wait at least 10 minutes between reboots
    minIntervalSeconds: 600
  revisionHistory:
    limit: 3
  paused: false

---
# =============================================================================
# MachineConfig: Kernel module (requires reboot)
# =============================================================================
apiVersion: mco.in-cloud.io/v1alpha1
kind: MachineConfig
metadata:
  name: kernel-module-config
  labels:
    mco.in-cloud.io/pool: production
spec:
  priority: 30
  files:
    # Load kernel module at boot
    - path: /etc/modules-load.d/custom.conf
      content: |
        # Load custom kernel modules
        br_netfilter
        overlay
        ip_vs
        ip_vs_rr
        ip_vs_wrr
        ip_vs_sh
      mode: 420
      owner: "root:root"
      state: present

    # Sysctl for the modules
    - path: /etc/sysctl.d/99-kubernetes.conf
      content: |
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward = 1
      mode: 420
      owner: "root:root"
      state: present

  reboot:
    # This requires reboot to load kernel modules
    required: true
    reason: "Kernel modules require reboot to load"

---
# =============================================================================
# MachineConfig: Simple config (no reboot)
# =============================================================================
apiVersion: mco.in-cloud.io/v1alpha1
kind: MachineConfig
metadata:
  name: simple-config
  labels:
    mco.in-cloud.io/pool: production
spec:
  priority: 50
  files:
    - path: /etc/myapp/config.conf
      content: |
        key = value
      mode: 420
      owner: "root:root"

  reboot:
    # This doesn't require reboot
    required: false
